### ISSUE TITLE
Link results from geotrellis nighly runs with User Dashboards: 

### ISSUE THREAD

**Issue by logoul** [wri/gfw_forest_loss_geotrellis_arcpy_client#2]
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**
Link results from geotrellis nighly runs with User Dashboards

**Additional context**
Gluing things together.
Step function: fetch geometries from the API, include in the directory that has user submitted geometries, include in the existing analysis, monitor that job succeeded, inject into the api and notify dashboard service that run was successful

**Comment by thomas-maschler** [comment]
wrong repo
